In [6]:
import torch
from torch.nn import NLLLoss

In [7]:
#define nansum, as pytorch does not offer it inbuild
def nansum(x):
    return x[~torch.isnan(x)].sum()

In [8]:
def self_information(p):
    return -torch.log2(torch.tensor(p)).item()

In [9]:
self_information(1 / 64)

6.0

In [10]:
#entropy
def entropy(p):
    entropy = -p * torch.log2(p)
    print(entropy)
    out = nansum(entropy)
    return out


In [11]:
entropy(torch.tensor([0.1, 0.5, 0.1, 0.3]))

tensor([0.3322, 0.5000, 0.3322, 0.5211])


tensor(1.6855)

In [12]:
x = torch.tensor([0.1, 0.5, 0.1, 0.3])
x

tensor([0.1000, 0.5000, 0.1000, 0.3000])

In [13]:
xx = torch.isnan(x)
xx

tensor([False, False, False, False])

In [14]:
x[~xx]

tensor([0.1000, 0.5000, 0.1000, 0.3000])

In [15]:
import numpy as np
np.random.random_sample(size = (3,2))

array([[0.39863845, 0.64328885],
       [0.17964653, 0.87449279],
       [0.59404319, 0.47594586]])

In [18]:
# joint probability
def joint_entropy(p_xy):
    joint_enp = -p_xy * torch.log2(p_xy)
    out = nansum(joint_enp)
    return out

In [19]:
joint_entropy(torch.tensor([[0.1, 0.5], [0.1, 0.3]]))

tensor(1.6855)

In [26]:
#conditional entropy
def conditional_entropy(p_xy, p_x):
    p_y_given_x = p_xy / p_x
    print(p_y_given_x)
    cond_ent = -p_xy * torch.log2(p_y_given_x)
    out = nansum(cond_ent)
    return out


In [27]:
conditional_entropy(torch.tensor([[0.1, 0.5], [0.2, 0.3]]), torch.tensor([0.2, 0.8]))

tensor([[0.5000, 0.6250],
        [1.0000, 0.3750]])


tensor(0.8635)

In [38]:
#mutual information
def mutual_information(p_xy, p_x, p_y):
    p = p_xy / (p_x * p_y)
    mutual = p_xy * torch.log2(p)
    out = nansum(mutual)
    return out

In [39]:
mutual_information(torch.tensor([[0.1, 0.5], [0.1, 0.3]]), torch.tensor([0.2, 0.8]), torch.tensor([[0.75, 0.25]]))

tensor(0.7195)

In [41]:
# ex on KL divergence
# generate 3 tensors of length 10,000.
# p: (objective tensor) followa a normal dist N(0, 1)
# q1: normal distribution N(-1, 1)
# q2: Normal disttribution N(1, 1)


In [55]:
def kl_divergence(p, q):
    kl = p * torch.log2(p / q)
    out = nansum(kl)
    return out.abs().item()

In [56]:
torch.manual_seed(1)
tensor_len = 10000
p = torch.normal(0, 1, (tensor_len,))
q1 = torch.normal(-1, 1, (tensor_len,))
q2 = torch.normal(1, 1, (tensor_len,))

In [57]:
p

tensor([-1.5256, -0.7502, -0.6540,  ...,  0.8306,  0.3967, -0.8857])

In [58]:
p = torch.sort(p)[0]
q1 = torch.sort(q1)[0]
q2 = torch.sort(q2)[0]

In [59]:
p

tensor([-4.1841, -3.9455, -3.7402,  ...,  3.3628,  3.4057,  3.8027])

In [61]:
kl_pq1 = kl_divergence(p, q1)
kl_pq2 = kl_divergence(p, q2)
similarity_percentage = abs(kl_pq1 - kl_pq2) / ((kl_pq1 + kl_pq2) / 2) * 100
print(kl_pq1, kl_pq2, similarity_percentage)

8582.0341796875 8828.3095703125 2.8290698237936858


In [63]:
kl_q2p = kl_divergence(q2, p)
difference_percentage = abs(kl_q2p - kl_pq2) ((kl_q2p + kl_pq2) / 2) * 100
print(kl_q2p, difference_percentage)

TypeError: 'float' object is not callable

In [69]:
def cross_entropy(y_hat, y):
    print([range(len(y_hat)), y])
    print(y_hat[range(len(y_hat)), y])
    ce = -torch.log(y_hat[range(len(y_hat)), y])
    return ce.mean()


In [70]:
labels = torch.tensor([0, 2])
preds = torch.tensor([[0.3, 0.6, 0.1], [0.2, 0.3, 0.5]])
cross_entropy(preds, labels)

[range(0, 2), tensor([0, 2])]
tensor([0.3000, 0.5000])


tensor(0.9486)

In [71]:
range(len(preds))

range(0, 2)

In [28]:
!pip install sympy

Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple



[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [29]:
from sympy import *

In [30]:
!pip install latexify-py

Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple



[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
import math
import latexify

@latexify.function
def quadratic_formula(a, b, c):
    return (-b + ((b**2 - 4*a*c)**0.5)) / (2*a)

print(quadratic_formula)

\mathrm{quadratic\_formula}(a, b, c) = \frac{-b + \mathopen{}\left( b^{2} - 4 a c \mathclose{}\right)^{0.5}}{2 a}


In [32]:
import math
import latexify
import sympy as sp  # pip install sympy module first

@latexify.function
def integrate_example():
    x = sp.symbols('x')
    f = x**2 + 5*x + 6
    integral = sp.integrate(f, x)
    return integral

print(integrate_example)

\begin{array}{l} x = \mathrm{sp}.\mathrm{symbols} \mathopen{}\left( \textrm{"x"} \mathclose{}\right) \\ f = x^{2} + 5 x + 6 \\ \mathrm{integral} = \mathrm{sp}.\mathrm{integrate} \mathopen{}\left( f, x \mathclose{}\right) \\ \mathrm{integrate\_example}() = \mathrm{integral} \end{array}


In [33]:
import math
import latexify

@latexify.with_latex
def piecewise(x):
    if x < 0:
        return -x
    else:
        return x**2
print(piecewise)

AttributeError: module 'latexify' has no attribute 'with_latex'

In [34]:
import math
import latexify
import sympy as sp  

@latexify.expression
def symbolic_expression():
    x, y = sp.symbols('x y')
    expression = (x + y)**3
    return expression

print(symbolic_expression)

\begin{array}{l} \mathopen{}\left( x, y \mathclose{}\right) = \mathrm{sp}.\mathrm{symbols} \mathopen{}\left( \textrm{"x y"} \mathclose{}\right) \\ \mathrm{expression} = \mathopen{}\left( x + y \mathclose{}\right)^{3} \\ \mathrm{expression} \end{array}
